Permissions:
  addBlockPermission: "obreak.add"
  deleteBlockPermission: "obreak.delete"
  editBlockPermission: "obreak.edit"
  defaultBreakBlockFormat: "obreak.break."
  addDisabledWorld: "obreak.disableWorld"
  removeDisabledWorld: "obreak.disableWorld"

blocks: