Block: "Block"
Permission: "Permission"

AddBlockPermission: "onlybreak.addblock"
RemoveBlockPermission: "onlybreak.removeblock"
BlockListPermission: "onlybreak.blocklist"
BlockGUIPermission: "onlybreak.blockgui"

blocks: