message:
  warn-perm: "Non sei di un RANK abbastanza alto per rompere questo blocco oppure non hai il permesso"

permissions:
  coalore: "break.coalore"
  ironore: "break.ironore"
  redstoneore: "break.redstoneore"
  lapisore: "break.lapisore"
  goldore: "break.goldore"
  diamondore: "break.diamondore"
  emeraldore: "break.emeraldore"
  coalblock: "break.coalblock"
  ironblock: "break.ironblock"
  redstoneblock: "break.redstoneblock"
  lapisblock: "break.lapisblock"
  goldblock: "break.goldblock"
  diamondblock: "break.diamondblock"
  emeraldblock: "break.emeraldblock"

permissions2:
  - "break.coalore"
  - "break.ironore"
  - "break.redstoneore"
  - "break.lapisore"
  - "break.goldore"
  - "break.diamondore"
  - "break.emeraldore"
  - "break.coalblock"
  - "break.ironblock"
  - "break.redstoneblock"
  - "break.lapisblock"
  - "break.goldblock"
  - "break.diamondblock"
  - "break.emeraldblock"

blocks:
  - "COAL_ORE"
  - "IRON_ORE"
  - "REDSTONE_ORE"
  - "LAPIS_ORE"
  - "GOLD_ORE"
  - "DIAMOND_ORE"
  - "EMERALD_ORE"
  - "COAL_BLOCK"
  - "IRON_BLOCK"
  - "REDSTONE_BLOCK"
  - "LAPIS_BLOCK"
  - "GOLD_BLOCK"
  - "DIAMOND_BLOCK"
  - "EMERALD_BLOCK"