Block: "Block"
Permission: "Permission"

AddBlockPermission: "Onlybreak.addblock"
RemoveBlockPermission: "Onlybreak.removeblock"
BlockListPermission: "Onlybreak.blocklist"
BlockGUIPermission: "Onlybreak.blockgui"
OnlyBreak-command-permission: "Onlybreak.Onlybreak"
MyBlocks-Enabled: true
MyBlocks-Enable-Permission: false
MyBlocks-Permission: "Onlybreak.myblocks"

blocks: