message:
  warn-perm-block: "You need to be of an higher rank or you don't have the permission"
  warn-perm: "You don't have the permissions to do this command"
  warn-format: "Invalid format, use /addblock <BLOCK_NAME> <break.permission>, for example /addblock COAL_ORE break.coalore"
  warn-format-remove: "Invalid format, use /removeblock <BLOCK_NAME> <break.permission>, for example /removeblock COAL_BLOCK break.coalore"
  command-correct: "Command executed with success!"
  warn-NotAPlayer: "You aren't a player!"
  warn-NotMaterial: "That material doesn't exist"
  warn-NotMaterialAdvice: "Check the config and remove the block"
  NotValidBlockID: "BARRIER"

permissions:
  - "break.coalore"
  - "break.ironore"
  - "break.redstoneore"
  - "break.lapisore"
  - "break.goldore"
  - "break.diamondore"
  - "break.emeraldore"
  - "break.coalblock"
  - "break.ironblock"
  - "break.redstoneblock"
  - "break.lapisblock"
  - "break.goldblock"
  - "break.diamondblock"
  - "break.emeraldblock"

blocks:
  - "COAL_ORE"
  - "IRON_ORE"
  - "REDSTONE_ORE"
  - "LAPIS_ORE"
  - "GOLD_ORE"
  - "DIAMOND_ORE"
  - "EMERALD_ORE"
  - "COAL_BLOCK"
  - "IRON_BLOCK"
  - "REDSTONE_BLOCK"
  - "LAPIS_BLOCK"
  - "GOLD_BLOCK"
  - "DIAMOND_BLOCK"
  - "EMERALD_BLOCK"

Block: "Block"
Permission: "Permission"

AddBlockPermission: "onlybreak.addblock"
RemoveBlockPermission: "onlybreak.removeblock"
BlockListPermission: "onlybreak.blocklist"
BlockGUIPermission: "onlybreak.blockgui"