message:
  warn-perm: "Non sei di un RANK abbastanza alto per rompere questo blocco oppure non hai il permesso"

permissions:
  - "break.coalore"
  - "break.ironore"
  - "break.redstoneore"
  - "break.lapisore"
  - "break.goldore"
  - "break.diamondore"
  - "break.emeraldore"
  - "break.coalblock"
  - "break.ironblock"
  - "break.redstoneblock"
  - "break.lapisblock"
  - "break.goldblock"
  - "break.diamondblock"
  - "break.emeraldblock"

blocks:
  - "COAL_ORE"
  - "IRON_ORE"
  - "REDSTONE_ORE"
  - "LAPIS_ORE"
  - "GOLD_ORE"
  - "DIAMOND_ORE"
  - "EMERALD_ORE"
  - "COAL_BLOCK"
  - "IRON_BLOCK"
  - "REDSTONE_BLOCK"
  - "LAPIS_BLOCK"
  - "GOLD_BLOCK"
  - "DIAMOND_BLOCK"
  - "EMERALD_BLOCK"