message:
  warn-perm-block: "Non sei di un RANK abbastanza alto per rompere questo blocco oppure non hai il permesso"
  warn-perm: "Non hai il permesso per eseguire questo comando"
  warn-format: "Format non corretto, utilizzare /addblock <BLOCK_NAME> <break.permission>, ad esempio /addblock COAL_ORE break.coalore"
  warn-format-remove: "Format non corretto, utilizzare /removeblock <BLOCK_NAME> <break.permission>, ad esempio /removeblock COAL_BLOCK break.coalore"
  command-correct: "Comando eseguito correttamente"
  warn-NotAPlayer: "Non sei un player!"

permissions:
  - "break.coalore"
  - "break.ironore"
  - "break.redstoneore"
  - "break.lapisore"
  - "break.goldore"
  - "break.diamondore"
  - "break.emeraldore"
  - "break.coalblock"
  - "break.ironblock"
  - "break.redstoneblock"
  - "break.lapisblock"
  - "break.goldblock"
  - "break.diamondblock"
  - "break.emeraldblock"

blocks:
  - "COAL_ORE"
  - "IRON_ORE"
  - "REDSTONE_ORE"
  - "LAPIS_ORE"
  - "GOLD_ORE"
  - "DIAMOND_ORE"
  - "EMERALD_ORE"
  - "COAL_BLOCK"
  - "IRON_BLOCK"
  - "REDSTONE_BLOCK"
  - "LAPIS_BLOCK"
  - "GOLD_BLOCK"
  - "DIAMOND_BLOCK"
  - "EMERALD_BLOCK"

Block: "Blocco"
Permission: "Permesso"

AddBlockPermission: "onlybreak.addblock"
RemoveBlockPermission: "onlybreak.removeblock"
BlockListPermission: "onlybreak.blocklist"
BlockGUIPermission: "onlybreak.blockgui"