name: OnlyBreak
version: 1.3.4
author: GABRYCA
main: it.gabryca.onlybreak.Main
website: https://www.gabryca.tk
api-version: 1.13
commands:
  AddBlock:
    description: Add a block to the config blocks list and a permission
    usage: /<command> <Block_Name> <break.Permission>
  BlockList:
    description: Give a list of blocks and permissions in the chat
    usage: /<command>
  BlockGUI:
    description: Open a GUI with a list of the blocks and their permissions
    usage: /<command>
  DelBlock:
    description: Remove a block from the config
    usage: /<command> <Block_Name>
  MyBlocks:
    description: See which blocks you can break in a GUI
    usage: /<command>